INSERT INTO USER_WALLET (BALANCE, CURRENCY, USER_ID) VALUES
(50000.00, 'USDT', 'ZI_JIAN'),
(1.00, 'ETH', 'ZI_JIAN'),
(0.00, 'BTC', 'ZI_JIAN');

INSERT INTO TRADE_TRANSACTION (USER_ID, SYMBOL, ACTION, QUANTITY, PRICE, TIMESTAMP) VALUES
('ZI_JIAN', 'USDT', 'BUY', 1.00, 100.00, CURRENT_TIMESTAMP()),
('ZI_JIAN', 'ETHUSDT', 'SELL', 0.5, 2400.00, CURRENT_TIMESTAMP()),
('ZI_JIAN', 'BTCUSDT', 'BUY', 0.1, 50000.75, CURRENT_TIMESTAMP());